(load-file "swedish-strings.el")
(setq a (copy-sequence lyskom-strings))
(load-file "english-strings.el")
(setq b (copy-sequence lyskom-strings))

(with-output-to-temp-buffer "*diffs*"
  (while (or a b)
    (cond
     ((eq (car (car a)) (car (car b)))
      (setq a (cdr a))
      (setq b (cdr b)))
     ((eq (cdr (car a)) 'found)
      (setq a (cdr a)))
     ((eq (cdr (car b)) 'founc)
      (setq b (cdr b)))
     ((assoc (car (car a)) b)
      (setcdr (assoc (car (car a)) b) 'found)
      (setq a (cdr a)))
     ((assoc (car (car b)) a)
      (setcdr (assoc (car (car b)) a) 'found)
      (setq b (cdr b)))
     (t
      (prin1 (format "%s -- %s" (car a) (car b)))
      (terpri)
      (setq a (cdr a))
      (setq b (cdr b))))))
