#!/usr/bin/perl

# This script is really simple and someone can probably write a much
# better version of it. I wanted to do a sed version, but advanced sed
# isn't all that portable and besides, I was tired and didn't get it
# right the first time. Hence perl. I'd like to get rid of the perl.

# The script ignores everything up to the first line containing
# <chapter>. The assumption is that this is on a line of its own. It
# then prints everything until we see a line with </chapter>, which is
# also assumed to be on a line of its own.

$p = 0;
while ($line = <STDIN>) {

   if ($line =~ /<chapter>/) {
        $p = 1;
   }
   if ($line =~ /<\/chapter>/) {
        print $line;
        exit 0;
   }
   print $line if $p;
}

exit 1
